# Generated by Django 3.2.20 on 2023-08-25 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='usser',
            new_name='user',
        ),
    ]
